// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xciuindvfatryangdunx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaXVpbmR2ZmF0cnlhbmdkdW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NTY2OTksImV4cCI6MjA3MzAzMjY5OX0.wVOj-wVWKM8wUq1tUOq0fhijO_r9WipKmqCiy-33Ewc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});